### ISSUE TITLE
Hangs on invalid strings

### ISSUE THREAD

**Issue by Kerl13** [tree-sitter/tree-sitter-ocaml#26] opened 2019-03-30 16:49 UTC
When parsing the example code given below, tree-sitter-ocaml hangs forever and incurs a very high CPU usage and memory consumption.

```
===========
Invalid strings
===========
let _ = "\"
---
(compilation_unit
 (value_definition
  (let_binding
   (value_name)
   (string (escape_sequence) (MISSING)))))
```

This can be annoying since it happens every time one wants to write `\n` at the end of a string in Atom

**Comment by 314eter** [comment] 2019-03-30 19:29
This was caused by my attempt to allow null characters in strings, and is fixed in #27.

**Closed** 2019-04-05 20:00 UTC
